### ISSUE TITLE
Import / Export / Sync from/to iCloud Keychain

### ISSUE THREAD

**Issue by patrickstigler** [strongbox-password-safe/Strongbox#409]
# Task Description

I would like to migrate all my passwords from iCloud Keychain. In the best case I'd like to sync my Passwords from/to iCloud with my Keepass container. Since I also use different OS/Hardware I don't want to Lookup my updated password I updated using my iphone on the PC and update it in the Keepass container manually.

# Tasks

The following tasks will need to be carried out:
* [ ] Manage to import from iCloud Keychain
* [ ] Manage to export from iCloud Keychain
* [ ] Update / Sync in both ways - check last changed

**Comment by micheledicosmo** [comment]
👍

**Comment by S474N** [comment]
+1

**Comment by strongbox-mark** [comment]
Just a heads up, this is now available (full CSV import/export compatibility) with iCloud Keychain in 1.58.6 on the App Store now. :)
